import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/auth-context";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/themes/theme-provider";
import { ReactQueryProvider } from "@/context/react-query-provider";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Rex | Social Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <ReactQueryProvider>
        <AuthContextProvider>
          <body className={`${roboto.className} bg-card h-full`}>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
            <Toaster />
          </body>
        </AuthContextProvider>
      </ReactQueryProvider>
    </html>
  );
}
